const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DATA=p=>fetch(p).then(r=>r.json());
$('#menuBtn')?.addEventListener('click',()=>$('#drawer').classList.add('open'));$('#closeBtn')?.addEventListener('click',()=>$('#drawer').classList.remove('open'));
function countdown(){const el=$('#countdown');if(!el)return;const target=new Date('2026-07-06T20:00:00');const diff=target-new Date();const d=Math.max(0,Math.floor(diff/864e5));const h=Math.max(0,Math.floor(diff/36e5)%24);const m=Math.max(0,Math.floor(diff/6e4)%60);const s=Math.max(0,Math.floor(diff/1e3)%60);el.innerHTML=[['Giorni',d],['Ore',h],['Minuti',m],['Secondi',s]].map(x=>`<div class="timebox"><b>${String(x[1]).padStart(2,'0')}</b><span>${x[0]}</span></div>`).join('')}setInterval(countdown,1000);countdown();
function slug(s){return s.toLowerCase().replaceAll(' ','-').replaceAll("'",'').replaceAll('à','a').replaceAll('è','e')}
async function home(){const teams=await DATA('data/teams.json');const matches=await DATA('data/matches.json');const editions=await DATA('data/editions.json');
 const t26=teams.filter(t=>t.edition===2026), t25=teams.filter(t=>t.edition===2025);$('#stats')&&( $('#stats').innerHTML=`<div class="card stat"><b>${t26.length||'—'}</b><p>Squadre 2026</p></div><div class="card stat"><b>9</b><p>Giorni di torneo</p></div><div class="card stat"><b>2025</b><p>Archivio storico</p></div><div class="card stat"><b>1</b><p>Campione finale</p></div>`);
 $('#teamsGrid')&&( $('#teamsGrid').innerHTML=t25.map(t=>`<a class="card team-card" href="team/?id=${t.id}" style="--c1:${t.colors[0]};--c2:${t.colors[1]}"><div class="team-dot"></div><h3>${t.name}</h3><p class="muted">${t.players.length} giocatori registrati</p></a>`).join(''));
 const recent=matches.filter(m=>m.homeScore!==null).slice(-5).reverse();$('#matches')&&( $('#matches').innerHTML=recent.map(m=>`<div class="match"><b>${m.home}</b><div class="score">${m.homeScore} - ${m.awayScore}</div><b>${m.away}</b><small class="muted">${m.stage} · ${new Date(m.date).toLocaleDateString('it-IT')}</small></div>`).join(''));
}
home();
async function teamPage(){const root=$('#teamPage');if(!root)return;const teams=await DATA('../data/teams.json');const id=new URLSearchParams(location.search).get('id');const t=teams.find(x=>x.id===id)||teams[0];document.title=t.name+' | Torneo Calcetto Capodacqua';root.innerHTML=`<section class="section"><div class="container"><div class="card" style="--c1:${t.colors[0]};--c2:${t.colors[1]}"><div class="team-dot"></div><p class="kicker">Squadra ufficiale</p><h1>${t.name}</h1><p class="muted">Edizione ${t.edition}${t.coach?` · Allenatore: ${t.coach}`:''}</p></div><h2>Rosa</h2><div class="grid">${t.players.map(p=>`<div class="card"><h3>${p}</h3><p class="muted">Giocatore</p></div>`).join('')}</div></div></section>`}
teamPage();
